In [2]:
import requests
import pandas as pd

In [2]:
def main():
    url = "https://archive-api.open-meteo.com/v1/archive"
    cities = [
        { "name": "Karachi", "country": "Pakistan", "latitude": 24.8608, "longitude": 67.0104 },
        { "name": "Trivandrum", "country": "India", "latitude":8.4855, "longitude": 76.9492 },
        { "name": "Mangalore", "country": "India", "latitude": 12.9172, "longitude": 74.856},
        { "name": "Old Goa", "country": "India", "latitude": 15.4438, "longitude": 73.8857 },
        { "name": "Mumbai ", "country": "India", "latitude": 19.0728, "longitude": 72.8826 },
        { "name": "Surat", "country": "India", "latitude": 21.1959, "longitude": 72.8302 },
        { "name": "Bhuj", "country": "India", "latitude": 23.254, "longitude": 69.6693 },
    ]
    cities_df =[]
    for city in cities:
        params = {"latitude":city["latitude"],
                "longitude":city['longitude'],
                "start_date": "2010-01-01",
                "end_date": "2023-08-06",
                "daily": "weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,sunset,shortwave_radiation_sum,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,windspeed_10m_max,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration",
                "timezone": "GMT",
                "min": "2010-01-01",
                "max": "2023-08-06",
        }
        res = requests.get(url, params=params)

        data = res.json()
        #print(data)
        df = pd.DataFrame(data["daily"])
        df["latitude"] = data["latitude"]
        df["longitude"] = data["longitude"]
        df["elevation"] = data["elevation"]
        df["country"] = city["country"]
        df["city"] = city["name"]
        cities_df.append(df)
    concat_df = pd.concat(cities_df, ignore_index=True)
    concat_df.to_csv('open_meteo.csv')



if __name__ == "__main__":
    main()

In [3]:
df = pd.read_csv('open_meteo.csv')
df

,Unnamed: 0,time,weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,...,precipitation_hours,windspeed_10m_max,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration,latitude,longitude,elevation,country,city
0,0,2010-01-01,0,26.0,14.8,20.9,24.0,13.4,18.6,2010-01-01T02:16,...,0.0,18.3,25.6,54,4.38,24.900002,67.0,8.0,Pakistan,Karachi
1,1,2010-01-02,2,25.3,15.6,20.5,21.8,13.7,18.1,2010-01-02T02:17,...,0.0,24.6,35.3,64,3.84,24.900002,67.0,8.0,Pakistan,Karachi
2,2,2010-01-03,0,25.0,14.3,19.9,22.8,14.2,18.9,2010-01-03T02:17,...,0.0,16.6,28.1,312,3.69,24.900002,67.0,8.0,Pakistan,Karachi
3,3,2010-01-04,0,25.6,15.0,20.4,23.9,13.7,19.4,2010-01-04T02:17,...,0.0,14.0,22.7,353,3.63,24.900002,67.0,8.0,Pakistan,Karachi
4,4,2010-01-05,0,25.4,16.3,20.7,24.5,16.8,20.7,2010-01-05T02:17,...,0.0,19.3,29.2,270,3.55,24.900002,67.0,8.0,Pakistan,Karachi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34757,34757,2023-08-02,51,30.2,25.5,27.4,31.5,27.8,29.3,2023-08-02T00:52,...,6.0,37.7,58.3,238,4.07,23.300003,69.7,105.0,India,Bhuj
34758,34758,2023-08-03,51,30.4,25.4,27.3,31.5,28.2,29.7,2023-08-03T00:52,...,10.0,36.4,56.2,238,3.92,23.300003,69.7,105.0,India,Bhuj
34759,34759,2023-08-04,51,30.5,25.5,27.5,32.8,29.3,30.6,2023-08-04T00:52,...,6.0,31.8,49.3,234,3.75,23.300003,69.7,105.0,India,Bhuj
34760,34760,2023-08-05,51,30.7,25.6,27.5,32.5,28.9,30.4,2023-08-05T00:53,...,6.0,30.7,48.6,239,4.10,23.300003,69.7,105.0,India,Bhuj
34761,34761,2023-08-06,51,30.7,25.4,27.3,31.7,27.0,28.9,2023-08-06T00:53,...,4.0,38.8,60.5,240,4.31,23.300003,69.7,105.0,India,Bhuj

In [4]:
df.groupby('country').get_group('India')

,Unnamed: 0,time,weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,...,precipitation_hours,windspeed_10m_max,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration,latitude,longitude,elevation,country,city
4966,4966,2010-01-01,51,29.8,23.5,26.5,35.7,26.8,30.8,2010-01-01T01:06,...,3.0,8.7,24.1,135,4.37,8.500000,76.899994,12.0,India,Trivandrum
4967,4967,2010-01-02,2,29.2,23.7,26.2,34.9,26.2,29.9,2010-01-02T01:06,...,0.0,12.1,22.0,15,4.44,8.500000,76.899994,12.0,India,Trivandrum
4968,4968,2010-01-03,2,29.5,23.8,26.2,34.1,27.0,29.7,2010-01-03T01:07,...,0.0,14.7,30.2,182,4.29,8.500000,76.899994,12.0,India,Trivandrum
4969,4969,2010-01-04,51,28.7,24.4,26.1,33.0,27.5,29.6,2010-01-04T01:07,...,3.0,14.0,26.3,208,3.75,8.500000,76.899994,12.0,India,Trivandrum
4970,4970,2010-01-05,2,28.8,22.1,25.8,32.8,25.9,29.6,2010-01-05T01:08,...,0.0,15.1,29.5,274,3.86,8.500000,76.899994,12.0,India,Trivandrum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34757,34757,2023-08-02,51,30.2,25.5,27.4,31.5,27.8,29.3,2023-08-02T00:52,...,6.0,37.7,58.3,238,4.07,23.300003,69.700000,105.0,India,Bhuj
34758,34758,2023-08-03,51,30.4,25.4,27.3,31.5,28.2,29.7,2023-08-03T00:52,...,10.0,36.4,56.2,238,3.92,23.300003,69.700000,105.0,India,Bhuj
34759,34759,2023-08-04,51,30.5,25.5,27.5,32.8,29.3,30.6,2023-08-04T00:52,...,6.0,31.8,49.3,234,3.75,23.300003,69.700000,105.0,India,Bhuj
34760,34760,2023-08-05,51,30.7,25.6,27.5,32.5,28.9,30.4,2023-08-05T00:53,...,6.0,30.7,48.6,239,4.10,23.300003,69.700000,105.0,India,Bhuj
34761,34761,2023-08-06,51,30.7,25.4,27.3,31.7,27.0,28.9,2023-08-06T00:53,...,4.0,38.8,60.5,240,4.31,23.300003,69.700000,105.0,India,Bhuj

In [5]:
df[df['country']=='India']

,Unnamed: 0,time,weathercode,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,...,precipitation_hours,windspeed_10m_max,windgusts_10m_max,winddirection_10m_dominant,et0_fao_evapotranspiration,latitude,longitude,elevation,country,city
4966,4966,2010-01-01,51,29.8,23.5,26.5,35.7,26.8,30.8,2010-01-01T01:06,...,3.0,8.7,24.1,135,4.37,8.500000,76.899994,12.0,India,Trivandrum
4967,4967,2010-01-02,2,29.2,23.7,26.2,34.9,26.2,29.9,2010-01-02T01:06,...,0.0,12.1,22.0,15,4.44,8.500000,76.899994,12.0,India,Trivandrum
4968,4968,2010-01-03,2,29.5,23.8,26.2,34.1,27.0,29.7,2010-01-03T01:07,...,0.0,14.7,30.2,182,4.29,8.500000,76.899994,12.0,India,Trivandrum
4969,4969,2010-01-04,51,28.7,24.4,26.1,33.0,27.5,29.6,2010-01-04T01:07,...,3.0,14.0,26.3,208,3.75,8.500000,76.899994,12.0,India,Trivandrum
4970,4970,2010-01-05,2,28.8,22.1,25.8,32.8,25.9,29.6,2010-01-05T01:08,...,0.0,15.1,29.5,274,3.86,8.500000,76.899994,12.0,India,Trivandrum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34757,34757,2023-08-02,51,30.2,25.5,27.4,31.5,27.8,29.3,2023-08-02T00:52,...,6.0,37.7,58.3,238,4.07,23.300003,69.700000,105.0,India,Bhuj
34758,34758,2023-08-03,51,30.4,25.4,27.3,31.5,28.2,29.7,2023-08-03T00:52,...,10.0,36.4,56.2,238,3.92,23.300003,69.700000,105.0,India,Bhuj
34759,34759,2023-08-04,51,30.5,25.5,27.5,32.8,29.3,30.6,2023-08-04T00:52,...,6.0,31.8,49.3,234,3.75,23.300003,69.700000,105.0,India,Bhuj
34760,34760,2023-08-05,51,30.7,25.6,27.5,32.5,28.9,30.4,2023-08-05T00:53,...,6.0,30.7,48.6,239,4.10,23.300003,69.700000,105.0,India,Bhuj
34761,34761,2023-08-06,51,30.7,25.4,27.3,31.7,27.0,28.9,2023-08-06T00:53,...,4.0,38.8,60.5,240,4.31,23.300003,69.700000,105.0,India,Bhuj